name: Push to API
on:
  push:
  workflow_dispatch:

env:
  version: '1.20.2'
  branch: 'ver/1.20.2'
  debug: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - name: Setup Action
        uses: actions/checkout@v3
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'

      - name: Configure Git and Gradle
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          echo "workflow=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
          chmod +x gradlew

       - name: Push to Api
      continue-on-error: true
      if: "!contains(github.event.commits[0].message, '[release-skip]')"
      env:
        secret: ${{ secrets.API_PUSH_TOKEN }}
        secret_v2: ${{ secrets.API_V2_PUSH_TOKEN }}
        tag: ${{ env.tag }}
      run: sh scripts/PushToAPI.sh
